#!/bin/bash
# a Sample bash script
if [ -z "$1" ]
  then
    echo "No argument supplied"
    exit
fi
cd ./platforms/browser
rsync --exclude assets/* -avz --delete . "eyc_proveedores@newton.eycproveedores.com:htdocs/$1/admin" 

echo "syncronized"