#!/bin/bash
# a Sample bash script
cd ./platforms/browser/www

folder="plazueladetoscan"
rsync --exclude=assets/header.js -avz --delete . "gabriel@residentesonline.com:htdocs/$folder/admin" 

folder="cretaricaurte"
rsync --exclude=assets/header.js -avz --delete . "gabriel@residentesonline.com:htdocs/$folder/admin" 

folder="santoriniricaurte"
rsync --exclude=assets/header.js -avz --delete . "gabriel@residentesonline.com:htdocs/$folder/admin" 

folder="bellasuiza"
rsync --exclude=assets/header.js -avz --delete . "gabriel@residentesonline.com:htdocs/$folder/admin" 

folder="horizontesdelcastillo"
rsync --exclude=assets/header.js -avz --delete . "gabriel@residentesonline.com:htdocs/$folder/admin" 

echo "syncronized"
cd ../../../