export const langs = {
   "backup":{
      "backup":"Copia de seguridad",
      "create_a_new_backup":"Crear una copia de seguridad",
      "existing_backups":"Copias de seguridad existentes",
      "date":"Fecha",
      "file_size":"Tama\u00f1o del fichero",
      "actions":"Acciones",
      "download":"Descargar",
      "delete":"Eliminar",
      "delete_confirm":"\u00bfEst\u00e1s seguro que quieres borrar esta copia de seguridad?",
      "delete_confirmation_title":"Confirmado",
      "delete_confirmation_message":"La copia de seguridad fue eliminada.",
      "delete_error_title":"Ups, ha ocurrido un error",
      "delete_error_message":"La copia de seguridad NO se pudo eliminar.",
      "delete_cancel_title":"La operaci\u00f3n ha sido cancelada",
      "delete_cancel_message":"La copia de seguridad NO se pudo eliminar.",
      "create_confirmation_title":"Se ha completado la copia de seguridad",
      "create_confirmation_message":"Recargando la p\u00e1gina en 3 segundos.",
      "create_error_title":"Error al realizar la copia de seguridad",
      "create_error_message":"La copia de seguridad NO se pudo crear.",
      "create_warning_title":"Estamos presentando problemas",
      "create_warning_message":"La copia de seguridad puede que no se haya realizado. Por favor verifica los logs para m\u00e1s detalles.",
      "location":"Ubicaci\u00f3n",
      "no_disks_configured":"No existe ning\u00fan disco configurado config\/laravel-backup.php",
      "backup_doesnt_exist":"La copia de seguridad no existe.",
      "only_local_downloads_supported":"Solo se permiten descargas del sistema de archivos local."
   },
   "base":{
      "registration_closed":"El registro de usuarios est\u00e1 cerrado.",
      "first_page_you_see":"La p\u00e1gina que ves despu\u00e9s de iniciar sesi\u00f3n",
      "login_status":"Estado de la conexi\u00f3n",
      "logged_in":"\u00a1Usted ha iniciado sesi\u00f3n!",
      "toggle_navigation":"Activar\/desactivar la navegaci\u00f3n",
      "administration":"ADMINISTRACI\u00d3N",
      "user":"USUARIO",
      "logout":"Salir",
      "login":"Iniciar sesi\u00f3n",
      "register":"Crear usuario",
      "name":"Nombre",
      "email_address":"Correo",
      "password":"Contrase\u00f1a",
      "confirm_password":"Confirmar contrase\u00f1a",
      "remember_me":"Recordar contrase\u00f1a",
      "forgot_your_password":"\u00bfOlvid\u00f3 su contrase\u00f1a?",
      "reset_password":"Restaurar contrase\u00f1a",
      "send_reset_link":"Enviar enlace para restaurar la contrase\u00f1a",
      "click_here_to_reset":"Click aqu\u00ed para restaurar la contrase\u00f1a",
      "unauthorized":"No autorizado.",
      "dashboard":"Panel",
      "handcrafted_by":"Realizado por",
      "powered_by":"Creado con",
      "file_manager":"Administrador de Archivos"
   },
   "crud":{
      "save_action_save_and_new":"Guardar y crear nuevo",
      "save_action_save_and_edit":"Guardar y continuar editando",
      "save_action_save_and_back":"Guardar y regresar",
      "save_action_changed_notification":"La acci\u00f3n por defecto del bot\u00f3n guardar ha sido modificada.",
      "add":"A\u00f1adir",
      "back_to_all":"Volver al listado de",
      "cancel":"Cancelar",
      "add_a_new":"A\u00f1adir ",
      "back":"Atras",
      "proccess":"Procesar",
      "edit":"Editar",
      "save":"Guardar",
      "apply":"Aplicar",
      "select":"Seleccionar",
      "reject":"Rechazar",
      "selecteds":"Seleccionados",
      "revisions":"revisiones",
      "no_revisions":"No hay revisiones encontradas",
      "created_this":"ha creado este",
      "changed_the":"ha cambiado el valor",
      "restore_this_value":"restaurar este valor",
      "from":"de",
      "to":"a",
      "undo":"Deshacer",
      "revision_restored":"Revisi\u00f3n restaurada correctamente",
      "all":"Todos los registros de ",
      "in_the_database":"en la base de datos",
      "list":"Listar",
      "actions":"Acciones",
      "preview":"Vista previa",
      "delete":"Eliminar",
      "admin":"Admin",
      "details_row":"Esta es la fila de detalles. Modificar a su gusto.",
      "details_row_loading_error":"Se ha producido un error al cargar los datos. Por favor, intente de nuevo.",
      "delete_confirm":"\u00bfEst\u00e1 seguro que desea eliminar este elemento?",
      "delete_confirmation_title":"Elemento eliminado",
      "delete_confirmation_message":"El elemento ha sido eliminado de manera correcta.",
      "delete_confirmation_not_title":"No se pudo eliminar",
      "delete_confirmation_not_message":"Ha ocurrido un error. Puede que el elemento no haya sido eliminado.",
      "delete_confirmation_not_deleted_title":"No se pudo eliminar",
      "delete_confirmation_not_deleted_message":"No ha ocurrido nada. Su elemento est\u00e1 seguro.",
      "emptyTable":"No hay datos disponibles en la tabla",
      "info":"Mostrando registros _START_ a _END_ de un total de _TOTAL_ registros",
      "infoEmpty":"Mostrando 0 registros",
      "infoFiltered":"(filtrando de _MAX_ registros totales)",
      "infoPostFix":"",
      "thousands":",",
      "lengthMenu":"_MENU_ elementos por p\u00e1gina",
      "loadingRecords":"Cargando...",
      "processing":"Procesando...",
      "search":"Buscar: ",
      "zeroRecords":"No se encontraron elementos",
      "paginate":{
         "first":"Primero",
         "last":"\u00daltimo",
         "next":"Siguiente",
         "previous":"Anterior"
      },
      "export":{
         "copy":"Copiar",
         "excel":"Excel",
         "csv":"Csv",
         "pdf":"Pdf",
         "print":"Imprimir",
         "column_visibility":"Columnas"
      },
      "aria":{
         "sortAscending":": activar para ordenar ascendentemente",
         "sortDescending":": activar para ordenar descendentemente"
      },
      "unauthorized_access":"Acceso denegado - usted no tiene los permisos necesarios para ver esta p\u00e1gina.",
      "please_fix":"Por favor corrija los siguientes errores:",
      "insert_success":"El elemento ha sido a\u00f1adido de manera correcta.",
      "update_success":"El elemento ha sido modificado de manera correcta.",
      "reorder":"Reordenar",
      "reorder_text":"Arrastrar y soltar para reordenar.",
      "reorder_success_title":"Hecho",
      "reorder_success_message":"El orden ha sido guardado.",
      "reorder_error_title":"Error",
      "reorder_error_message":"El orden no se ha guardado.",
      "yes":"S\u00ed",
      "no":"No",
      "upload":"Subir",
      "browse_uploads":"Subir archivos",
      "close":"Cerrar",
      "clear":"Limpiar",
      "filter":"Filtro",
      "filters":"Filtros",
      "remove filters":"Remover Filtros",
      "page_link":"Enlace",
      "page_link_placeholder":"http:\/\/example.com\/su-pagina",
      "internal_link":"Enlace interno",
      "internal_link_placeholder":"Slug interno. Ejplo: 'admin\/page' (sin comillas) para ':url'",
      "external_link":"Enlace externo",
      "file_manager":"Administrador de Archivos",
      "created":"creado",
      "updated":"actualizado",
      "deleted":"borrado",
      "Today":"Hoy",
      "Yesterday":"Ayer",
      "Last 7 Days":"Ultimos 7 Dias",
      "Last 30 Days":"Ultimos 30 Dias",
      "This Month":"Este Mes",
      "Last Month":"Ultimo Mes"
   },
   "date":{
      "date":"Fecha",
      "day":"D\u00eda",
      "days":"Dias",
      "month":"Mes",
      "year":"A\u00f1o",
      "from":"Del",
      "to":"Hasta",
      "hour":"Hora",
      "hours":"Horas",
      "minute":"Minuto",
      "minutes":"Minutos",
      "monday":"Lunes",
      "tuesday":"Martes",
      "wednesday":"Miercoles",
      "thursday":"Jueves",
      "friday":"Viernes",
      "saturday":"Sabado",
      "sunday":"Domingo",
      "date range":"Rango de Fechas",
      "second":"Segundo",
      "day name":"Nombre del D\u00eda",
      "month name":"Nombre del mes",
      "last 7 days":"Ultimos 7 D\u00edas",
      "last 30 days":"Ultimos 30 D\u00edas",
      "next":"Pr\u00f3ximo",
      "tomorrow":"Ma\u00f1ana",
      "today":"Hoy",
      "yesterday":"Ayer",
      "week":"Esta Semana",
      "this_week":"Esta Semana",
      "last_week":"Semana Pasada",
      "this_month":"Este Mes",
      "last_month":"Mes Pasado",
      "this_year":"Este A\u00f1o",
      "last_year":"El A\u00f1o Pasado",
      "older":"Antiguos"
   },
   "emails":{
      "hello":"Hola :Name",
      "invoice_paid":"Una de tus :invoices ha sido pagada! ",
      "new_invoice":"Tienes una nueva :invoice",
      "footer":"Gracias por usar Residencias Online",
      "regards":"Saludos"
   },
   "finances":{
      "payment_received":":payment recibido",
      "payment_accepted":":payment aceptado",
      "payment_rejected":":payment rechazado"
   },
   "installer_messages":{
      "title":"Instalador de Residentes Online",
      "next":"Siguiente Paso",
      "back":"Anterios",
      "finish":"Instalar",
      "forms":{
         "errorTitle":"Ha ocurrido el siguiente error:"
      },
      "welcome":{
         "templateTitle":"Bienvenido",
         "title":"Instalador  de Residentes Online",
         "message":"Instalacion Facil.",
         "next":"Comprobar Requisitos"
      },
      "requirements":{
         "templateTitle":"Paso 1 | Requerimientos del servidor",
         "title":"Requerimientos",
         "next":"Chequear Permisos"
      },
      "permissions":{
         "templateTitle":"Paso 2 | Permisos",
         "title":"Permisos",
         "next":"Configurar Permisos en el servidor"
      },
      "environment":{
         "menu":{
            "templateTitle":"Paso 3 | Variables de Configuracion",
            "title":"Variables de Configuracion",
            "desc":"Selecciona como configurar la instalacion.",
            "wizard-button":"Form Wizard Setup",
            "classic-button":"Editor de Texto"
         },
         "wizard":{
            "templateTitle":"Paso 3 | Variables de Configuracion | Guided Wizard",
            "title":"Guided <code>.env<\/code> Wizard",
            "tabs":{
               "environment":"Environment",
               "database":"Database",
               "application":"Application"
            },
            "form":{
               "name_required":"An environment name is required.",
               "app_name_label":"App Name",
               "app_name_placeholder":"App Name",
               "app_environment_label":"App Environment",
               "app_environment_label_local":"Local",
               "app_environment_label_developement":"Development",
               "app_environment_label_qa":"Qa",
               "app_environment_label_production":"Production",
               "app_environment_label_other":"Other",
               "app_environment_placeholder_other":"Enter your environment...",
               "app_debug_label":"App Debug",
               "app_debug_label_true":"True",
               "app_debug_label_false":"False",
               "app_log_level_label":"App Log Level",
               "app_log_level_label_debug":"debug",
               "app_log_level_label_info":"info",
               "app_log_level_label_notice":"notice",
               "app_log_level_label_warning":"warning",
               "app_log_level_label_error":"error",
               "app_log_level_label_critical":"critical",
               "app_log_level_label_alert":"alert",
               "app_log_level_label_emergency":"emergency",
               "app_url_label":"App Url",
               "app_url_placeholder":"App Url",
               "db_connection_label":"Database Connection",
               "db_connection_label_mysql":"mysql",
               "db_connection_label_sqlite":"sqlite",
               "db_connection_label_pgsql":"pgsql",
               "db_connection_label_sqlsrv":"sqlsrv",
               "db_host_label":"Database Host",
               "db_host_placeholder":"Database Host",
               "db_port_label":"Database Port",
               "db_port_placeholder":"Database Port",
               "db_name_label":"Database Name",
               "db_name_placeholder":"Database Name",
               "db_username_label":"Database User Name",
               "db_username_placeholder":"Database User Name",
               "db_password_label":"Database Password",
               "db_password_placeholder":"Database Password",
               "app_tabs":{
                  "more_info":"More Info",
                  "broadcasting_title":"Broadcasting, Caching, Session, &amp; Queue",
                  "broadcasting_label":"Broadcast Driver",
                  "broadcasting_placeholder":"Broadcast Driver",
                  "cache_label":"Cache Driver",
                  "cache_placeholder":"Cache Driver",
                  "session_label":"Session Driver",
                  "session_placeholder":"Session Driver",
                  "queue_label":"Queue Driver",
                  "queue_placeholder":"Queue Driver",
                  "redis_label":"Redis Driver",
                  "redis_host":"Redis Host",
                  "redis_password":"Redis Password",
                  "redis_port":"Redis Port",
                  "mail_label":"Mail",
                  "mail_driver_label":"Mail Driver",
                  "mail_driver_placeholder":"Mail Driver",
                  "mail_host_label":"Mail Host",
                  "mail_host_placeholder":"Mail Host",
                  "mail_port_label":"Mail Port",
                  "mail_port_placeholder":"Mail Port",
                  "mail_username_label":"Mail Username",
                  "mail_username_placeholder":"Mail Username",
                  "mail_password_label":"Mail Password",
                  "mail_password_placeholder":"Mail Password",
                  "mail_encryption_label":"Mail Encryption",
                  "mail_encryption_placeholder":"Mail Encryption",
                  "pusher_label":"Pusher",
                  "pusher_app_id_label":"Pusher App Id",
                  "pusher_app_id_palceholder":"Pusher App Id",
                  "pusher_app_key_label":"Pusher App Key",
                  "pusher_app_key_palceholder":"Pusher App Key",
                  "pusher_app_secret_label":"Pusher App Secret",
                  "pusher_app_secret_palceholder":"Pusher App Secret"
               },
               "buttons":{
                  "setup_database":"Setup Database",
                  "setup_application":"Setup Application",
                  "install":"Install"
               }
            }
         },
         "classic":{
            "templateTitle":"Paso 3 | Variables de Configuracion | Editor",
            "title":"Edicion de Variables (Clasisco)",
            "save":"Guardar .env",
            "back":"Usar Asistente",
            "install":"Guardar e instalar"
         },
         "success":"tu archivo .env fue guardado.",
         "errors":"Unable to Guardar the .env file, Please create it manually."
      },
      "install":"Instalar",
      "installed":{
         "success_log_message":"Residentes Online Instalado Correctamente "
      },
      "final":{
         "title":"Instalacion  Finalizada",
         "templateTitle":"Instalacion Finalizada",
         "finished":"La Aplicacion ha sido instalada correctamente",
         "migration":"Alimentacion de base de datos &amp; Consola:",
         "console":"Application Console Output:",
         "log":"Log Entry:",
         "env":"Final .env File:",
         "exit":"Click aqui para salir"
      },
      "updater":{
         "title":"Residentes Online Actualizador",
         "welcome":{
            "title":"Bienvenido al actualizador",
            "message":"Welcome to the update wizard."
         },
         "overview":{
            "title":"Overview",
            "message":"There is 1 update.|There are :number updates.",
            "install_updates":"Install Updates"
         },
         "final":{
            "title":"Finished",
            "finished":"Application's database has been successfully updated.",
            "exit":"Click here to exit"
         },
         "log":{
            "success_message":"Residentes Online Instalador actualizador "
         }
      }
   },
   "langfilemanager":{
      "active":"Activo",
      "cant_edit_online":"Este Idioma no puede ser editado online.",
      "code_iso639-1":"Codido (ISO 639-1)",
      "default":"Defecto",
      "empty_file":"No hay traducciones disponibles.",
      "flag_image":"imagen Bandera",
      "key":"Key",
      "language":"lenguaje",
      "language_name":"Nombre del Lenguaje",
      "language_text":"texto en  :language_name",
      "language_translation":"traducci\u00f3n en :language_name",
      "languages":"Lenguajes",
      "please_fill_all_fields":"Por favor, rellene todos los campos",
      "rules_text":"<strong>Nota: <\/strong> Do not translate words prefixed with colon (ex: ':number_of_items'). Those will be replaced automatically with a proper value. If translated, that stops working.",
      "saved":"Guardado",
      "site_texts":"Textos del sitio",
      "switch_to":"Cambiar a",
      "texts":"Textos",
      "translate":"Tradduci\u00f3n",
      "translations":"Tradduciones",
      "native_name":"Nombre nativo"
   },
   "literals":{
      "opened_at":"Abierta el",
      "open":"Abierto",
      "opens":"Abiertos",
      "actions":"Acciones",
      "action":"Acci\u00f3n",
      "about":"Acerca",
      "is active":"Esta Activo",
      "active":"Activo",
      "actives":"Activos",
      "inactive":"Inactivo",
      "inactives":"Inactivos",
      "notification":"Notificaci\u00f3n",
      "notifications":"Notificaciones",
      "authorization":"Autorizaci\u00f3n",
      "authorizations":"Autorizaciones",
      "update":"Actualizar",
      "aditional":"Adicional",
      "additional":"Adicional",
      "administration":"Administraci\u00f3n",
      "administrator":"Administrador",
      "add":"Agregar",
      "solvents":"Al d\u00eda",
      "solvent":"Al d\u00eda",
      "ambulance":"Ambulancia",
      "apartment":"Apartamento",
      "last_name":"Apellidos",
      "approved_f":"Aprobada",
      "approveds_f":"Aprobadas",
      "approved":"Aprobado",
      "approveds":"Aprobados",
      "balance":"Saldo",
      "balances":"Saldos",
      "current balance":"Saldo Actual",
      "file":"Archivo",
      "files":"Archivos",
      "zone":"Area",
      "zones":"Areas",
      "subject":"Asunto",
      "audit":"Auditoria",
      "audits":"Auditorias",
      "advanced":"Avanzado",
      "banner":"Banner",
      "banners":"Banners",
      "bus":"Bus",
      "search":"Buscar",
      "every":"Cada",
      "van":"Camioneta",
      "field":"Campo",
      "fields":"Campos",
      "extras":"Campos Adicionales",
      "cancelled":"Anulado",
      "canceled_at":"Anulado el",
      "cancelleds":"Anulados",
      "quantity":"Cantidad",
      "characteristics":"Caracteristicas",
      "charge":"Cargo",
      "charges":"Cargos",
      "car":"Carro",
      "golf_cart":"Carro de golf",
      "house":"Casa",
      "category":"Categoria",
      "categories":"Categorias",
      "document":"Cedula",
      "closed_at":"Cerrada el",
      "closed":"Cerrado",
      "closeds":"Cerrados",
      "in proccess":"En proceso",
      "logout":"Cerrar Sesi\u00f3n",
      "check":"Cheque",
      "cash_desk":"Cierre de Caja",
      "cash_desks":"Cierre de Cajas",
      "customer":"Cliente",
      "customers":"Clientes",
      "alicuota":"Coeficiente",
      "color":"Color",
      "comunity":"Comunidad",
      "comunities":"Comunidades",
      "in_discount":"Con Descuento",
      "in_interest":"Con Intereses de mora",
      "concept":"Concepto",
      "owner":"Propietario",
      "owners":"Propietarios",
      "guest":"Invitado",
      "guests":"Invitados",
      "settings":"Configuraci\u00f3n",
      "confirm":"Confirmar",
      "password_confirmation":"Confirmar Contrase\u00f1a",
      "emergency_contact":"Contacto de Emergencia",
      "content":"Contenido",
      "password":"Contrase\u00f1a",
      "spouse":"Conyuge",
      "correspondence":"Correspondencia",
      "correspondences":"Correspondencias",
      "creator":"Creador",
      "creators":"Creadores",
      "payable_account":"Cuenta por Cobrar",
      "payable_accounts":"Cuentas por Cobrar",
      "quota":"Cuota",
      "quotas":"Cuotas",
      "deposit":"Deposito",
      "download":"Descargar",
      "description":"Descripci\u00f3n",
      "featured":"Destacado",
      "show_feature":"Destacar en el catalogo",
      "detailed":"Detallado",
      "details":"Detalles",
      "debt":"Deuda",
      "debts":"Deudas",
      "dynamic":"Dinamico",
      "address":"Direcci\u00f3n",
      "directives":"Directiva",
      "directive":"Directivo",
      "available":"Disponible",
      "available_for_defaulter":"Disponible para moroso",
      "availables":"Disponibles",
      "dynamic_document":"Documento",
      "dynamic_documents":"Documentos",
      "delivery":"Domicilio",
      "deliveries":"Domicilios",
      "cash":"Efectivo",
      "example":"Ejemplo",
      "delete":"Eliminar",
      "email":"Email",
      "comunity_email":"Email",
      "in_proccess":"En Proceso",
      "survey":"Encuesta",
      "surveys":"Encuestas",
      "login":"Entrar",
      "login_with_Facebook":"Entrar Con Facebook",
      "login_with_Google":"Entrar Con Google",
      "delivered":"Entregado",
      "delivered_at":"Entregado el",
      "delivered at":"Entregado el",
      "departured_at":"Ido a las",
      "departured at":"Ido a las",
      "start_at":"Comienza el",
      "start at":"Comienza el",
      "end_at":"Termina el",
      "end at":"Termina el",
      "authorized by":"autorizado por",
      "sent":"Enviado",
      "send":"Enviar",
      "choose":"Escoger",
      "choose_file":"Escoger Archivo",
      "special":"Especial",
      "specie":"Especie",
      "warehouse":"Almac\u00e9n",
      "warehouses":"Almacenes",
      "waiting_for_confirmation":"Esperando Confirmaci\u00f3n",
      "waiting for confirmation":"Esperando Confirmaci\u00f3n",
      "waiting_for_approval":"Esperando por Aprobaci\u00f3n",
      "waiting for approval":"Esperando por Aprobaci\u00f3n",
      "status":"Estado",
      "apply":"Aplicar",
      "marital_status":"Estado Civil",
      "tag":"Etiqueta",
      "tags":"Etiquetas",
      "event":"Evento",
      "events":"Eventos",
      "export":"Exportar",
      "invoice":"Factura",
      "invoice_number":"Factura #",
      "invoices":"Facturas",
      "faileds":"Fallidos",
      "date":"Fecha",
      "birthday":"Fecha de Nacimiento",
      "dates":"Fechas",
      "sex_femenine":"Femenino",
      "end_date":"Fin",
      "finances":"Finanzas",
      "signature":"Firma",
      "signatures":"Firmas",
      "winner":"Ganador",
      "expense":"Gasto",
      "expenses":"Gastos",
      "generate":"Generar",
      "free":"Gratis",
      "group":"Grupo",
      "groups":"Grupos de Residencias",
      "brother":"Hermano",
      "son":"Hijo",
      "panic_logs":"Historial de Emergencias",
      "male":"Hombre",
      "schedule":"Horario",
      "schedules":"Horarios",
      "id":"ID",
      "ids":"Ids",
      "image":"Imagen",
      "images":"Imagenes",
      "import":"Importar",
      "print":"Imprimir",
      "tax":"Impuesto",
      "taxes":"Impuestos",
      "start_date":"Inicio",
      "boat":"Lancha",
      "language":"Lenguaje",
      "languages":"Lenguajes",
      "url":"Link",
      "list":"Lista",
      "lists":"Listas",
      "done":"Listo",
      "arrive":"Llegada",
      "local":"Local",
      "locals":"Locales",
      "lot":"Lote",
      "place":"Lugar",
      "places":"Lugares",
      "limit_user":"L\u00edmite de usuarios",
      "limit user":"L\u00edmite de usuarios",
      "model":"L\u00ednea",
      "make":"Marca",
      "mark_as":"Marcar como",
      "pet":"Mascota",
      "pets":"Mascotas",
      "sex_masculine":"Masculino",
      "amount":"Monto",
      "show_price":"Mostrar el precio en el catalogo",
      "show_stock":"Mostrar el stock en el catalogo",
      "bike":"Moto",
      "female":"Mujer",
      "method":"M\u00e9todo",
      "methods":"M\u00e9todos",
      "comunity_document":"NIT",
      "no":"No",
      "undefined":"No Definido",
      "no_generated":"No Generado",
      "unpaid":"No Pagado",
      "name":"Nombre",
      "first_name":"Nombres",
      "note":"Nota",
      "notes":"Notas",
      "post":"Noticia",
      "posts":"Noticias",
      "number_of_people":"Numero de personas",
      "never_reclaimed":"Nunca Reclamado",
      "number":"N\u00famero",
      "phone_number":"N\u00famero de Telefono",
      "numbers":"N\u00fameros",
      "occuped":"Ocupado",
      "other":"Otro",
      "tickets":"PQRs",
      "parent":"Padre",
      "parent category":"Categor\u00eda Padre",
      "parent categories":"Categorias Padre",
      "paid":"Pagado",
      "paid_at":"Pagado el",
      "paid_by":"Pagado por",
      "paid by":"Pagado por",
      "page":"Pagina",
      "pages":"Paginas",
      "payment":"Pago",
      "payments":"Pagos",
      "panic":"Emergencia",
      "panics":"Emergencias",
      "to":"Para",
      "lobby":"Control de Acceso",
      "parameter":"Parametro",
      "parameters":"Parametros",
      "partially_paid":"Parcialmente Pagado",
      "partially paid":"Parcialmente Pagado",
      "relationship":"Parentesco",
      "relationship_large":"Parentesco con el propietario",
      "parking":"Parqueadero",
      "parkings":"Parqueaderos",
      "pending":"Pendiente",
      "pendings":"Pendientes",
      "lost":"Perdido",
      "permission":"Permiso",
      "permissions":"Permisos",
      "person":"Persona",
      "persons":"Personas",
      "plate":"Placa",
      "percent":"Porcentaje",
      "slider":"Portada",
      "sliders":"Portadas",
      "price":"Precio",
      "residence":"Vivienda",
      "residences":"Viviendas",
      "question":"Pregunta",
      "questions":"Preguntas",
      "response":"Respuesta",
      "responses":"Respuestas",
      "privacity":"Privacidad",
      "product":"Producto",
      "products":"Productos",
      "breed":"Raza",
      "reason":"Raz\u00f3n",
      "receptor":"Receptor",
      "receptors":"Receptores",
      "rejected_f":"Rechazada",
      "rejecteds_f":"Rechazadas",
      "rejected":"Rechazado",
      "rejecteds":"Rechazados",
      "reject":"Rechazar",
      "receipt":"Recibo",
      "receipts":"Recibos",
      "reference":"Referencia",
      "references":"Referencias",
      "sign_in":"Registrarse",
      "rent":"Arriendo",
      "report":"Reporte",
      "reports":"Reportes",
      "reservations":"Reservaciones",
      "reservation":"Reservaci\u00f3n",
      "server":"Servidor",
      "servers":"Servidores",
      "home":"Inicio",
      "reserved":"Reservado",
      "reservate":"Reservar",
      "backup":"Respaldos",
      "backups":"Respaldo",
      "answer":"Respuesta",
      "resume_charges":"Resumen de Gastos",
      "role":"Rol",
      "roles":"Roles",
      "usage":"Uso",
      "roles_have_permission":"Roles que tienen permiso",
      "user_role_permission":"Roles y Permisos",
      "comment":"Seguimiento",
      "comments":"Seguimientos",
      "select":"Seleccionar",
      "select_:person":"Seleccionar Persona",
      "sex":"Sexo",
      "yes":"Si",
      "solvency":"Solvencia",
      "solvencys":"Solvencias",
      "stock":"Stock",
      "subtotal":"Subtotal",
      "size":"Tamano",
      "smart pay":"Pago Inteligente",
      "credit card":"Tarjeta de Cr\u00e9dito",
      "credit_card":"Tarjeta de Cr\u00e9dito",
      "debit card":"Tarjeta de Debito",
      "debit_card":"Tarjeta de Debito",
      "comunity_phone":"Telefono",
      "phone":"Tel\u00e9fono",
      "text":"Texto",
      "time":"Tiempo",
      "close_time":"Tiempo de cierre",
      "type":"Tipo",
      "title":"Titulo",
      "all(f)":"Todas",
      "all_day":"Todo el D\u00eda",
      "all":"Todos",
      "total":"Total",
      "worker":"Trabajador",
      "workers":"Trabajadores",
      "work":"Trabajo",
      "translates":"Traducciones",
      "translate":"Traducci\u00f3n",
      "transactions":"Transaciones",
      "transaction":"Transaci\u00f3n",
      "transfer":"Transferencia",
      "location":"Ubicaci\u00f3n",
      "user":"Usuario",
      "users":"Usuarios",
      "value":"Valor",
      "neighbor":"Vecino",
      "neighbors":"Vecinos",
      "vehicle":"Vehiculo",
      "vehicles":"Vehiculos",
      "seller":"Vendedor",
      "sellers":"Vendedores",
      "sync":"Sincronizar",
      "observations":"Observaciones",
      "with":"Con",
      "without":"Sin",
      "having":"Teniendo",
      "sell_without_stock":"Vendible sin Stock",
      "view_resource":"Ver",
      "visibility":"Visibilidad",
      "visit":"Visita",
      "visits":"Visitas",
      "special_visit":"Visita Especial",
      "visitor":"Visitante",
      "visitors":"Visitantes",
      "unkown_visitor":"Visitante Desconocido",
      "preview":"Vista Previa",
      "fingerprint sensor":"Lector de huellas",
      "fingerprint":"Huella Dactilar",
      "fingerprints":"Huellas",
      "votes":"Votos",
      "admin":"admin",
      "bicycle":"bicicleta",
      "end":"fin",
      "cat":"gatos",
      "departured":"ido",
      "start":"inicio",
      "interval":"intervalo",
      "duration":"Duraci\u00f3n",
      "item":"item",
      "items":"items",
      "arrival":"llegada",
      "logs":"logs",
      "my":"mi",
      "my_vote":"mi voto",
      "defaulter":"moroso",
      "defaulters":"morosos",
      "more":"m\u00e1s",
      "none":"ninguno",
      "normal":"normal",
      "profile":"perfil",
      "dog":"perro",
      "personal":"personal",
      "reservable":"reservable",
      "residential":"residencial",
      "ticket":"ticket",
      "your_vote":"tu voto",
      "vote":"voto",
      "meeting":"Reuni\u00f3n",
      "meetings":"Reuniones",
      "attender":"Asitente",
      "attenders":"Asitentes",
      "programmed":"Programada",
      "finished":"Terminada",
      "reprogrammed":"Reprogramada",
      "entry":"Entrada",
      "entries":"Entradas",
      "exit":"Salida",
      "exits":"Salidas",
      "entry_log":"Registro de Acceso",
      "entry_logs":"Registro de Accesos",
      "entry log":"Registro de Acceso",
      "entry logs":"Registro de Accesos"
   },
   "logmanager":{
      "log_manager":"Log Manager",
      "log_manager_description":"Ver, descargar y eliminar logs.",
      "actions":"Acciones",
      "delete_confirm":"Estas seguro de que quieres eliminar este archivo de log?",
      "back_to_all_logs":"Volver a los logs",
      "create_a_new_log":"Crear nuevo log",
      "date":"Fecha",
      "delete":"Eliminar",
      "delete_confirmation_title":"Hecho",
      "download":"Descargar",
      "delete_error_title":"Error",
      "existing_logs":"Logs Existentes",
      "file_size":"Tamano del archivo",
      "delete_cancel_title":"It&#039;s ok",
      "last_modified":"Ultima Modificacion",
      "logs":"Logs",
      "preview":"Ver",
      "delete_cancel_message":"El log no ha sido borrado",
      "delete_error_message":"El log no ha sido borrado",
      "delete_confirmation_message":"El log fue borrado existosamente",
      "log_file_doesnt_exist":"El archivo de log no existe"
   },
   "settings":{
      "name":"Nombre",
      "value":"Valor",
      "description":"Descripci\u00f3n",
      "setting_singular":"Parametro",
      "setting_plural":"Parametros"
   },
   "__":{
      "live support":"Chat de Soporte",
      "by":"por",
      "mys":"mis",
      "all":"Todo",
      "dynamic":"Dinamico",
      "classic":"Clasico",
      "public":"P\u00fablico",
      "private":"Privado",
      "reserved zones":":zones reservadas",
      "zone":"Zona",
      "no specified":"No Especificado",
      "of":"de",
      "party":"Fiesta",
      "reunion":"Reuni\u00f3n",
      "meeting":"Encuentro",
      "expose":"Exposici\u00f3n",
      "wedding":"Boda",
      "birthday":"Cumplea\u00f1os",
      "funeral":"Funeral",
      "date start":"Fecha inicio",
      "date end":"Fecha Fin",
      "Choose your option":"Escoge una opci\u00f3n",
      "update residences":"Actualizar Residencias",
      "view users":"Ver Usuarios",
      "relationship":"parentesco",
      "relationship_large":"parentesco con el propietario",
      "Residences with more Debt":"Con mas Deuda",
      "unpaid":"no pagado",
      "paid":"pagado",
      "partially paid":"parcialmente pagado",
      "cancelled":"cancelado",
      "no charge":"no cargado",
      "overdue":"atrasado",
      "fully refunded":"Reembolsado",
      "partially refunded":"parcialmente reembolsado",
      "waiting for approval":"esperando aprobaci\u00f3n",
      "solvent":"Al d\u00eda",
      "defaulter":"Moroso",
      "residence":"Residencia",
      "rent":"renta",
      "cash":"Efectivo",
      "check":"Cheque",
      "debit card":"Tarjeta de D\u00e9bito",
      "credit card":"Tarjeta de Cr\u00e9dito",
      "deposit":"Deposito",
      "transfer":"Transferencia",
      "percentual":"Porcentual",
      "residential":"Residencial",
      "unique":"\u00danico",
      "group":"Grupo",
      "available":"Disponible",
      "occuped":"Ocupado",
      "parking":"Parqueadero",
      "set departure":"Marcar como ido",
      "approve":"aprobar",
      "reject":"rechazar",
      "success":"\u00c9xito",
      "updated_successfully":"Actualizado Correctamente",
      "from":"De",
      "created_at":"Creado el",
      "updated_at":"Actualizado el",
      "deleted_at":"Eliminado el",
      "createds":"Creados",
      "go to":"Ir a",
      "open in maps":"Abrir en Mapas",
      "total charge":"Total en Gasto",
      "you have a new visit":"Tienes una visita",
      "advanced visit":"Visita Avanzada",
      "last visit":"Ultima :visit",
      "my visitors":"Mis :visitors",
      "my vehicles":"Mis :vehicles",
      "my workers":"Mis :workers",
      "my parkings":"Mis :parkings",
      "method":"Metodo",
      "report payment":"reportar pago",
      "send by mail":"enviar por correo",
      "print as pdf":"imprimir en pdf",
      "print options":"Opciones de Impresi\u00f3n",
      "name of residence":"nombre de la residencia",
      "residence percent":"percentual de la residencia",
      "status of residence":"status de la residencia",
      "quantity of person":"cantidad de personas",
      "phone of residence":"telefono de la residencia",
      "name of the person":"Nombre de la persona",
      "document of the person":"documento de la persona",
      "phone of the person":"telefono de la persona",
      "email of the person":"correo electronico",
      "image of the person":"imagen de la persona",
      "name of comunity":"Nombre de la comunidad",
      "address of comunity":"Direcci\u00f3n de la comunidad",
      "phone of comunity":"telefono de la comunidad",
      "account":"cuenta",
      "number of document":"numero de documento",
      "Geo Latitude":"Geo Latitud",
      "Geo Longitude":"Geo Longitud",
      "center image":"imagen centrada",
      "left image":"imagen alineada a la izquierda",
      "right image":"imagen alineada a la derecha",
      "car":"Carro",
      "bike":"Moto",
      "van":"Camioneta",
      "bicycle":"bicicleta",
      "boat":"Lancha",
      "golf cart":"Carro de golf",
      "bus":"Bus",
      "ambulance":"Ambulancia",
      "name of the owner":"Nombre del due\u00f1o",
      "document of the owner":"documento del due\u00f1o",
      "phone of the owner":"telefono del due\u00f1o",
      "email of the owner":"correo electronico",
      "image of the owner":"imagen del due\u00f1o",
      "Bad Request":"Solicitud Incorrecta",
      "Unauthorized Action":"Acci\u00f3n no Autorizada",
      "Forbidden":"Prohibido",
      "Not Found":"Pagina No Encontrado",
      "Internal Server Error":"Error Interno del servidor",
      "Network Error":"Error de Red",
      "Unauthorized":"No Autorizado",
      "Go to homepage":"Ir a la Pagina Principal",
      "no generated":"No Generada",
      "are you sure":"Estas Seguro?",
      "Are you sure you want to generate the invoices? this action will be delete all the previous invoices generated":"\u00bfEstas seguro de que quiere generar las facturas?. Esta acci\u00f3n borrara la facturas de este tipo previamente generadas para este periodo",
      "visit confirmed":":visit confirmada de :visitor",
      "hours to cancel reservation":"Horas para cancelar la reservaci\u00f3n",
      "number invoices to declare disabled":"Numero de Facturas para declarar Desactivado",
      "next events":"Proximos Eventos",
      "processed":"Procesado",
      "and others":" y otros ",
      "Thanks":"Gracias",
      "forgot password":"\u00bfOlvido su contrase\u00f1a?",
      "recover":"Recuperar",
      "recover password":"Recuperar Contrase\u00f1a",
      "hello":"Hola",
      "go in":"Entrar",
      "we assign to you a new password":"Hemos reestablecido tu contrase\u00f1a",
      "unkown visitor":"Visitante desconocido",
      "you have a reservation":"tienes una reservaci\u00f3n",
      "view user":"Ver usuario",
      "add users":"Agregar usuarios",
      "update users":"Actualizar usuarios",
      "delete users":"Eliminar usuarios",
      "view residences":"Ver residencias",
      "add residences":"Agregar residencias ",
      "delete residences":"Eliminar residencias",
      "view invoices":"Ver facturas",
      "add invoices":"A\u00f1adir facturas",
      "update invoices":"Actualizar facturas",
      "delete invoices":"Eliminar facturas",
      "view vehicles":"Ver vehiculos",
      "add vehicles":"Agregar vehiculos",
      "update vehicles":"Actualizar vehiculos",
      "delete vehicles":"Eliminar Vehiculos",
      "view workers":"Ver trabajadores",
      "add workers":"Agregar trabajadores",
      "update workers":"Actualizar trabajadores",
      "delete workers":"Eliminar trabajadores",
      "view visitors":"Ver visitantes",
      "add visitors":"Agregar visitantes",
      "update visitors":"Actualizar visitantes",
      "delete visitors":"Eliminar visitantes",
      "view parkings":"Ver parqueaderos",
      "add parkings":"Agregar parqueaderos",
      "update parkings":"Actualizar parqueaderos",
      "delete parkings":"Eliminar parqueaderos",
      "view pets":"Ver mascotas",
      "add pets":"Agregar mascotas",
      "update pets":"Actualizar mascotas",
      "delete pets":"Eliminar mascotas",
      "view sliders":"Ver portadas",
      "add sliders":"Agregar portadas",
      "update sliders":"Actualizar portadas",
      "delete sliders":"Eliminar portadas",
      "view reservations":"Ver reservaciones",
      "add reservations":"Agregar reservaciones",
      "update reservations":"Actualizar reservaciones",
      "delete reservations":"Eliminar reservaciones",
      "view directives":"Ver directivas",
      "add directives":"Agregar directivas",
      "update directives":"Actualizar directivas",
      "delete directives":"Eliminar directivas",
      "view zones":"Ver areas",
      "add zones":"Agregar areas",
      "update zones":"Actualizar areas",
      "delete zones":"Eliminar areas",
      "view events":"Ver eventos",
      "add events":"Agregar eventos",
      "update events":"Actualizar eventos",
      "delete events":"Eliminar eventos",
      "view documents":"Ver documentos",
      "add documents":"Agregar documentos",
      "update documents":"Actualizar documentos",
      "delete documents":"Eliminar documentos",
      "view posts":"Ver noticias",
      "add posts":"Agregar noticias",
      "update posts":"Actualizar noticias",
      "delete posts":"Eliminar noticias",
      "view tags":"Ver tags",
      "add tags":"Agregar tags",
      "update tags":"Actualizar tags",
      "delete tags":"Eliminar tags",
      "view groups":"Ver grupos de residencias",
      "add groups":"Agregar grupos de residencias",
      "update groups":"Actualizar grupos de residencias",
      "delete groups":"Eliminar grupos de residencias",
      "view surveys":"Ver encuestas",
      "add surveys":"Agregar encuestas",
      "update surveys":"Actualizar encuestas",
      "delete surveys":"Eliminar encuestas",
      "view tickets":"Ver PQRs",
      "add tickets":"Agregar PQRs",
      "update tickets":"Actualizar PQRs",
      "delete tickets":"Eliminar PQRs",
      "view products":"Ver productos",
      "add products":"Agregar productos",
      "update products":"Actualizar productos",
      "delete products":"Eliminar productos",
      "view schedules":"Ver horarios",
      "add schedules":"Agregar horarios",
      "update schedules":"Actualizar horarios",
      "delete schedules":"Eliminar horarios",
      "view correspondences":"Ver correspondencias",
      "add correspondences":"Agregar correspondencias",
      "update correspondences":"Actualizar correspondencias",
      "delete correspondences":"Eliminar correspondencias",
      "view charges":"Ver cargos",
      "add charges":"Agregar cargos",
      "update charges":"Actualizar cargos",
      "delete charges":"Eliminar cargos",
      "view expenses":"Ver gastos",
      "add expenses":"Agregar gastos",
      "update expenses":"Actualizar gastos",
      "delete expenses":"Eliminar gastos",
      "Manage users":"Administrar usuarios",
      "Manage residences":"Administrar residencias",
      "Manage groups":"Administrar grupos de residencias",
      "Manage invoices":" Administrar facturas",
      "Manage vehicles":" Administrar vehiculos",
      "Manage workers":" Administrar trabajadores",
      "Manage visitors":" Administrar visitantes",
      "Manage parkings":"Administrar parqueaderos",
      "Manage pets":"Administrar mascotas",
      "Manage sliders":"Administrar portadas",
      "Manage reservations":"Administrar reservaciones",
      "Manage directives":"Administrar directiva",
      "Manage zones":"Administrar areas",
      "Manage events":"Administrar eventos",
      "Manage documents":"Administrar documentos",
      "Manage surveys":"Administrar encuestas",
      "Manage posts":"Administrar noticias",
      "Manage tags":"Administrar tags",
      "Manage tickets":"Administrar tickets",
      "Manage products":"Administrar productos",
      "Manage schedules":"Administrar horarios",
      "Manage panic logs":"Administrar historial de emergencias",
      "Manage correspondences":"Administrar correspondencias",
      "Manage expenses":"Administrar gastos",
      "Manage charges":"Administrar cargos",
      "Manage receipts":"Administrar recibos",
      "Finance":"Finanzista",
      "Celator":"Celador",
      "Accounter":"Contador",
      "Reports":"Reportes",
      "days discount invoices":"Dias en que la factura tendra descuento",
      "percent discount invoices":"Porcentaje de descuento por pago anticipado",
      "days interest invoices":"Dias que deben cumplirse para el  interes por mora en facturas",
      "percent interest invoices":"Porcentaje de interes por mora",
      "reserve fund":"Fondo de Reserva",
      "Summary Usage":"Resumen de Uso",
      "summary":"Resumen",
      "use the current balance":"Usar el saldo actual de la vivienda"
   }
}