export const langs = {
  "backup": {
    "backup": "Copia de seguridad",
    "create_a_new_backup": "Crear una copia de seguridad",
    "existing_backups": "Copias de seguridad existentes",
    "date": "Fecha",
    "file_size": "Tamaño del fichero",
    "actions": "Acciones",
    "download": "Descargar",
    "delete": "Eliminar",
    "delete_confirm": "¿Estás seguro que quieres borrar esta copia de seguridad? ",
    "delete_confirmation_title": "Confirmado",
    "delete_confirmation_message": "La copia de seguridad fue eliminada.",
    "delete_error_title": "Ups, ha ocurrido un error",
    "delete_error_message": "La copia de seguridad NO se pudo eliminar.",
    "delete_cancel_title": "La operación ha sido cancelada",
    "delete_cancel_message": "La copia de seguridad NO se pudo eliminar.",
    "create_confirmation_title": "Se ha completado la copia de seguridad",
    "create_confirmation_message": "Recargando la página en 3 segundos.",
    "create_error_title": "Error al realizar la copia de seguridad",
    "create_error_message": "La copia de seguridad NO se pudo crear.",
    "create_warning_title": "Estamos presentando problemas",
    "create_warning_message": "La copia de seguridad puede que no se haya realizado.Por favor verifica los logs para más detalles.",
    "location": "Ubicación",
    "no_disks_configured": "No existe ningún disco configurado config/ laravel - backup.php",
    "backup_doesnt_exist": "La copia de seguridad no existe.",
    "only_local_downloads_supported": "Solo se permiten descargas del sistema de archivos local."
  },
  "base": {
    "registration_closed": "El registro de usuarios está cerrado.",
    "first_page_you_see": "La página que ves después de iniciar sesión",
    "login_status": "Estado de la conexión",
    "logged_in": "¡Usted ha iniciado sesión!",
    "toggle_navigation": "Activar/ desactivar la navegación",
    "administration": "ADMINISTRACIÓN",
    "user": "USUARIO",
    "logout": "Salir",
    "login": "Iniciar sesión",
    "register": "Crear usuario",
    "name": "Nombre",
    "email_address": "Correo",
    "password": "Contraseña",
    "confirm_password": "Confirmar contraseña",
    "remember_me": "Recordar contraseña",
    "forgot_your_password": "¿Olvidó su contraseña? ",
    "reset_password": "Restaurar contraseña",
    "send_reset_link": "Enviar enlace para restaurar la contraseña",
    "click_here_to_reset": "Click aquí para restaurar la contraseña",
    "unauthorized": "No autorizado.",
    "dashboard": "Panel",
    "handcrafted_by": "Realizado por",
    "powered_by": "Creado con",
    "file_manager": "Administrador de Archivos"
  },
  "crud": {
    "save_action_save_and_new": "Guardar y crear nuevo",
    "save_action_save_and_edit": "Guardar y continuar editando",
    "save_action_save_and_back": "Guardar y regresar",
    "save_action_changed_notification": "La acción por defecto del botón guardar ha sido modificada.",
    "add": "Añadir",
    "back_to_all": "Volver al listado de",
    "cancel": "Cancelar",
    "add_a_new": "Añadir ",
    "edit": "Editar",
    "save": "Guardar",
    "revisions": "revisiones",
    "no_revisions": "No hay revisiones encontradas",
    "created_this": "creado este",
    "changed_the": "cambiado el",
    "restore_this_value": "restaurar este valor",
    "from": "de",
    "to": "a",
    "undo": "Deshacer",
    "revision_restored": "Revisión restaurada correctamente",
    "all": "Todos los registros de ",
    "in_the_database": "en la base de datos",
    "list": "Listar",
    "actions": "Acciones",
    "preview": "Vista previa",
    "delete": "Eliminar",
    "admin": "Admin",
    "details_row": "Esta es la fila de detalles.Modificar a su gusto.",
    "details_row_loading_error": "Se ha producido un error al cargar los datos.Por favor, intente de nuevo.",
    "delete_confirm": "¿Está seguro que desea eliminar este elemento? ",
    "delete_confirmation_title": "Elemento eliminado",
    "delete_confirmation_message": "El elemento ha sido eliminado de manera correcta.",
    "delete_confirmation_not_title": "No se pudo eliminar",
    "delete_confirmation_not_message": "Ha ocurrido un error.Puede que el elemento no haya sido eliminado.",
    "delete_confirmation_not_deleted_title": "No se pudo eliminar",
    "delete_confirmation_not_deleted_message": "No ha ocurrido nada.Su elemento está seguro.",
    "emptyTable": "No hay datos disponibles en la tabla",
    "info": "Mostrando registros _START_ a _END_ de un total de _TOTAL_ registros",
    "infoEmpty": "Mostrando 0 registros",
    "infoFiltered": "(filtrando de _MAX_ registros totales)",
    "infoPostFix": "",
    "thousands": ", ",
    "lengthMenu": "_MENU_ elementos por página",
    "loadingRecords": "Cargando...",
    "processing": "Procesando...",
    "search": "Buscar: ",
    "zeroRecords": "No se encontraron elementos",
    "paginate": {
      "first": "Primero",
      "last": "Último",
      "next": "Siguiente",
      "previous": "Anterior"
    },
    "aria": {
      "sortAscending": ": activar para ordenar ascendentemente",
      "sortDescending": ": activar para ordenar descendentemente"
    },
    "unauthorized_access": "Acceso denegado - usted no tiene los permisos necesarios para ver esta página.",
    "please_fix": "Por favor corrija los siguientes errores: ",
    "insert_success": "El elemento ha sido añadido de manera correcta.",
    "update_success": "El elemento ha sido modificado de manera correcta.",
    "reorder": "Reordenar",
    "reorder_text": "Arrastrar y soltar para reordenar.",
    "reorder_success_title": "Hecho",
    "reorder_success_message": "El orden ha sido guardado.",
    "reorder_error_title": "Error",
    "reorder_error_message": "El orden no se ha guardado.",
    "yes": "Sí",
    "no": "No",
    "browse_uploads": "Subir archivos",
    "close": "Cerrar",
    "clear": "Limpiar",
    "page_link": "Enlace",
    "page_link_placeholder": "http://example.com/su-pagina",
    "internal_link": "Enlace interno",
    "internal_link_placeholder": "Slug interno. Ejplo: 'admin/page' (sin comillas) para ':url'",
    "external_link": "Enlace externo",
    "file_manager": "Administrador de Archivos",
    "created": "creado",
    "updated": "actualizado",
    "deleted": "borrado"
  },
  "date": {
    "date": "Fecha",
    "day": "Día",
    "month": "Mes",
    "year": "Año",
    "from": "Del",
    "hour": "Hora",
    "minute": "Minuto"
  },
  "emails": {
    "hello": "Hola :Name",
    "invoice_paid": "Una de tus :invoices ha sido pagada! ",
    "new_invoice": "Tienes una nueva :invoice",
    "footer": "Gracias por usar Residencias Online",
    "regards": "Saludos"
  },
  "finances": {
    "payment_received": ":payment recibido",
    "payment_accepted": ":payment aceptado",
    "payment_rejected": ":payment rechazado"
  },
  "langfilemanager": {
    "active": "Activo",
    "cant_edit_online": "Este Idioma no puede ser editado online.",
    "code_iso639-1": "Codido (ISO 639-1)",
    "default": "Defecto",
    "empty_file": "No hay traducciones disponibles.",
    "flag_image": "imagen Bandera",
    "key": "Key",
    "language": "lenguaje",
    "language_name": "Nombre del Lenguaje",
    "language_text": "texto en  :language_name",
    "language_translation": "traducción en :language_name",
    "languages": "Lenguajes",
    "please_fill_all_fields": "Por favor, rellene todos los campos",
    "rules_text": "<strong>Nota: </strong> Do not translate words prefixed with colon (ex: ':number_of_items'). Those will be replaced automatically with a proper value. If translated, that stops working.",
    "saved": "Guardado",
    "site_texts": "Textos del sitio",
    "switch_to": "Cambiar a",
    "texts": "Textos",
    "translate": "Traddución",
    "translations": "Tradduciones",
    "native_name": "Nombre nativo"
  },
  "literals": {
    "opened_at": "Abierta el",
    "actions": "Acciones",
    "action": "Acción",
    "update": "Actualizar",
    "additional": "Adicional",
    "aditional": "Adicional",
    "administration": "Administración",
    "administrator": "Administrador",
    "add": "Agregar",
    "solvents": "Al día",
    "solvent": "Al día",
    "residence": "Apartamento",
    "last_name": "Apellidos",
    "approved_f": "Aprobada",
    "approveds_f": "Aprobadas",
    "approved": "Aprobado",
    "approveds": "Aprobados",
    "file": "Archivo",
    "files": "Archivos",
    "zone": "Area",
    "zones": "Areas",
    "advanced": "Avanzado",
    "search": "Buscar",
    "canceled_at": "Cancelado el",
    "quantity": "Cantidad",
    "charge": "Cargo",
    "charges": "Cargos",
    "residences": "Apartamentos",
    "document": "Cedula",
    "logout": "Cerrar Sesión",
    "check": "Cheque",
    "alicuota": "Coeficiente",
    "color": "Color",
    "comunity": "Comunidad",
    "comunities": "Comunidades",
    "concept": "Concepto",
    "settings": "Configuración",
    "confirm": "Confirmar",
    "password_confirmation": "Confirmar Contraseña",
    "content": "Contenido",
    "password": "Contraseña",
    "creator": "Creador",
    "deposit": "Deposito",
    "download": "Descargar",
    "description": "Descripción",
    "details": "Detalles",
    "debt": "Deuda",
    "address": "Dirección",
    "directives": "Directiva",
    "directive": "Directivo",
    "available": "Disponible",
    "available_for_defaulter": "Disponible para moroso",
    "availables": "Disponibles",
    "dynamic_document": "Documento",
    "dynamic_documents": "Documentos",
    "cash": "Efectivo",
    "delete": "Eliminar",
    "email": "Email",
    "survey": "Encuesta",
    "surveys": "Encuestas",
    "login": "Entrar",
    "login_with_Facebook": "Entrar Con Facebook",
    "login_with_Google": "Entrar Con Google",
    "sent": "Enviado",
    "send": "Enviar",
    "choose_file": "Escoger Archivo",
    "waiting_for_confirmation": "Esperando Confirmación",
    "status": "Estado",
    "marital_status": "Estado Civil",
    "tag": "Etiqueta",
    "tags": "Etiquetas",
    "event": "Evento",
    "events": "Eventos",
    "invoice": "Factura",
    "invoice_number": "Factura #",
    "invoices": "Facturas",
    "date": "Fecha",
    "birthday": "Fecha de Nacimiento",
    "dates": "Fechas",
    "sex_femenine": "Femenino",
    "end_date": "Fin",
    "finances": "Finanzas",
    "winner": "Ganador",
    "expense": "Gasto",
    "expenses": "Gastos",
    "generate": "Generar",
    "group": "Grupo",
    "groups": "Grupos de Residencias",
    "male": "Hombre",
    "image": "Imagen",
    "images": "Imagenes",
    "start_date": "Inicio",
    "language": "Lenguaje",
    "languages": "Lenguajes",
    "url": "Link",
    "arrive": "Llegada",
    "model": "Línea",
    "make": "Marca",
    "mark_as": "Marcar como",
    "sex_masculine": "Masculino",
    "amount": "Monto",
    "female": "Mujer",
    "no": "No",
    "undefined": "No Definido",
    "unpaid": "No Pagado",
    "name": "Nombre",
    "first_name": "Nombres",
    "notes": "Notas",
    "post": "Noticia",
    "posts": "Noticias",
    "number_of_people": "Numero de personas",
    "number": "Número",
    "phone_number": "Número de Telefono",
    "numbers": "Números",
    "occuped": "Ocupado",
    "other": "Otro",
    "paid": "Pagado",
    "page": "Pagina",
    "pages": "Paginas",
    "payment": "Pago",
    "to": "Para",
    "parameters": "Parametros",
    "partially_paid": "Parcialmente Pagado",
    "parking": "Parqueadero",
    "parkings": "Parqueaderos",
    "permission": "Permiso",
    "permissions": "Permisos",
    "plate": "Placa",
    "slider": "Portada",
    "sliders": "Portadas",
    "question": "Pregunta",
    "privacity": "Privacidad",
    "owner": "Propietario",
    "rejected_f": "Rechazada",
    "rejecteds_f": "Rechazadas",
    "rejected": "Rechazado",
    "rejecteds": "Rechazados",
    "reject": "Rechazar",
    "receipt": "Recibo",
    "receipts": "Recibos",
    "sign_in": "Registrarse",
    "backup": "Resplados",
    "answer": "Respuesta",
    "resume_charges": "Resumen de Gastos",
    "role": "Rol",
    "roles": "Roles",
    "roles_have_permission": "Roles que tienen permiso",
    "user_role_permission": "Roles y Permisos",
    "sex": "Sexo",
    "yes": "Si",
    "solvency": "Solvencia",
    "solvencys": "Solvencias",
    "subtotal": "Subtotal",
    "credit_card": "Tarjeta Crédito",
    "debit_card": "Tarjeta Debito",
    "phone": "Teléfono",
    "text": "Texto",
    "close_time": "Tiempo de cierre",
    "type": "Tipo",
    "title": "Titulo",
    "all_day": "Todo el Día",
    "total": "Total",
    "worker": "Trabajador",
    "workers": "Trabajadores",
    "translates": "Traducciones",
    "translate": "Traducción",
    "transactions": "Transaciones",
    "transaction": "Transación",
    "transfer": "Transferencia",
    "location": "Ubicación",
    "user": "Usuario",
    "users": "Usuarios",
    "neighbor": "Vecino",
    "neighbors": "Vecinos",
    "vehicle": "Vehiculo",
    "vehicles": "Vehiculos",
    "view_resource": "Ver",
    "visibility": "Visibilidad",
    "visit": "Visita",
    "visitor": "Visitante",
    "visitors": "Visitantes",
    "visits": "Visitas",
    "preview": "Vista Previa",
    "admin": "admin",
    "departured": "ido",
    "logs": "logs",
    "my": "mi",
    "defaulter": "moroso",
    "defaulters": "morosos",
    "more": "más",
    "profile": "perfil"
  },
  "settings": {
    "name": "Nombre",
    "value": "Valor",
    "description": "Descripción",
    "setting_singular": "Parametro",
    "setting_plural": "Parametros"
  },
  "__": {
    "all": "Todo",
    "public": "Público",
    "private": "Privado",
    "reserved zones": ":zones reservadas",
    "zone": "Zona",
    "no specified": "No Especificado",
    "party": "Fiesta",
    "reunion": "Reunión",
    "meeting": "Encuentro",
    "expose": "Exposición",
    "wedding": "Boda",
    "birthday": "Cumpleaños",
    "funeral": "Funeral",
    "date start": "Fecha inicio",
    "date end": "Fecha Fin",
    "Choose your option": "Escoge una opción",
    "update residences": "Actualizar Residencias",
    "view users": "Ver Usuarios",
    "paid": "pagado",
    "partially paid": "parcialmente pagado",
    "solvent": "Al día",
    "defaulter": "Moroso",
    "residence": "Residencia",
    "rent": "renta",
    "cash": "Efectivo",
    "check": "Cheque",
    "debit card": "Tarjeta de Débito",
    "credit card": "Tarjeta de Crédito",
    "deposit": "Deposito",
    "transfer": "Transferencia",
    "percentual": "Porcentual",
    "residential": "Residencial",
    "unique": "Único",
    "available": "Disponible",
    "occuped": "Ocupado",
    "parking": "Parqueadero",
    "set departure": "Marcar como ido",
    "approve": "aprobar",
    "reject": "rechazar",
    "success": "Éxito",
    "updated_successfully": "Actualizado Correctamente",
    "from": "De",
    "created_at": "Creado el",
    "updated_at": "Actualizado el",
    "deleted_at": "Eliminado el",
    "total charge": "Total en Gasto",
    "you have a new visit": "Tienes una visita",
    "last visit": "Ultima :visit",
    "my visitors": "Mis :visitors",
    "my vehicles": "Mis :vehicles",
    "my workers": "Mis :workers",
    "my parkings": "Mis :parkings",
    "report payment": "reportar pago",
    "send by mail": "enviar por correo",
    "print as pdf": "imprimir en pdf",
    "name of residence": "nombre de la residencia",
    "residence percent": "percentual de la residencia",
    "status of residence": "status de la residencia",
    "quantity of person": "cantidad de personas",
    "phone of residence": "telefono de la residencia",
    "name of the person": "Nombre de la persona",
    "document of the person": "documento de la persona",
    "phone of the person": "telefono de la persona",
    "email of the person": "correo electronico",
    "image of the person": "imagen de la persona",
    "name of comunity": "Nombre de la comunidad",
    "address of comunity": "Dirección de la comunidad",
    "phone of comunity": "telefono de la comunidad",
    "account": "cuenta",
    "number of document": "numero de documento",
    "Geo Latitude": "Geo Latitud",
    "Geo Longitude": "Geo Longitud",
    "center image": "imagen centrada",
    "left image": "imagen alineada a la izquierda",
    "right image": "imagen alineada a la derecha",
    "name of the owner": "Nombre del dueño",
    "document of the owner": "documento del dueño",
    "phone of the owner": "telefono del dueño",
    "email of the owner": "correo electronico",
    "image of the owner": "imagen del dueño",
    "Bad Request": "Solicitud Incorrecta",
    "Unauthorized Action": "Acción no Autorizada",
    "Forbidden": "Prohibido",
    "Not Found": "Pagina No Encontrado",
    "Go to homepage": "Ir a la Pagina Principal",
    "Internal Server Error": "Error Interno del servidor",
    "are you sure": "Estas Seguro?",
    "visit confirmed": ":visit confirmada de :visitor",
    "next events": "Proximos Eventos",
    "Manage users": "Administrar Usuarios"
  }
}
